//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int M_id { get; set; }
        public int S_id { get; set; }
        public int Destination_id { get; set; }
        public string message1 { get; set; }
    
        public virtual user_t user_t { get; set; }
    }
}
