//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qa()
        {
            this.qa_comment = new HashSet<qa_comment>();
            this.qa_rating = new HashSet<qa_rating>();
        }
    
        public int Qa_id { get; set; }
        public int U_id { get; set; }
        public string Qa_title { get; set; }
        public string Qa_body { get; set; }
    
        public virtual user_t user_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_comment> qa_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_rating> qa_rating { get; set; }
    }
}
