//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_rating
    {
        public int User_rating_id { get; set; }
        public int U_id { get; set; }
        public Nullable<int> User_rating1 { get; set; }
        public string User_tag { get; set; }
    
        public virtual user_t user_t { get; set; }
    }
}
