//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vid_rating
    {
        public int Vid_rating_id { get; set; }
        public int Vid_id { get; set; }
        public int U_id { get; set; }
        public Nullable<int> Vid_rating1 { get; set; }
    
        public virtual video video { get; set; }
    }
}
