//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public video()
        {
            this.vid_comment = new HashSet<vid_comment>();
            this.vid_rating = new HashSet<vid_rating>();
        }
    
        public int Vid_id { get; set; }
        public int U_id { get; set; }
        public string Vid_title { get; set; }
        public string Vid_body { get; set; }
    
        public virtual user_t user_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vid_comment> vid_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vid_rating> vid_rating { get; set; }
    }
}
